"Inseason_CVIN_SMALL_GOAL_TEXT": "Evaluation of the Chlorophyll activity",
  "Inseason_CVIN_LONG_GOAL_TEXT": "Evaluation of the Chlorophyll activity from satellite images",
  "RX_MAP_PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR3_CVIN": "N Rec. Round 3 (Normal)",
  "PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR3_CVIN": "N Rec. Tour 3(Normal)",
  "PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR3_CVIN_WITHOUT": "N Rec. Tour 3",
  "RX_MAP_PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR3_INVERSE_CVIN": "N Rec. Round 3 Quality(Normal)",
  "PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR3_INVERSE_CVIN": "N Rec. Tour 3 Quality (Normal)",
  "PRODUCT_TYPE_DISPLAY_TEXT_IInSeasonPRECO_AZOTE_TOUR3_INVERSE_CVIN_WITHOUT": "N Rec. Tour 3 Quality",
  "RX_MAP_PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR4_CVIN": "N Rec. Round 4(Normal)",
  "PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR4_CVIN": "N Rec. Round 4 (Normal) ",
  "PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR4_CVIN_WITHOUT": "N Rec. Round 4",
  "InSeasonPRECO_AZOTE_TOUR4_CVIN_GOAL":"Goal: Adjust the nitrogen dose depending on the field variability.",
  "InSeasonPRECO_AZOTE_TOUR4_CVIN_DESC":"Adjust the nitrogen dose depending on the field variability and on the Chlorophyll map.",
  "InSeasonPRECO_AZOTE_TOUR4_INVERSE_CVIN_GOAL":"Goal: Adjust the nitrogen dose depending on the field variability.",
  "InSeasonPRECO_AZOTE_TOUR4_INVERSE_CVIN_DESC":"Adjust the nitrogen dose depending on the field variability and on the Chlorophyll map.",
  "InSeasonPRECO_AZOTE_TOUR3_CVIN_GOAL":"Goal: Adjust the nitrogen dose depending on the field variability.",
  "InSeasonPRECO_AZOTE_TOUR3_CVIN_DESC":"Adjust the nitrogen dose depending on the field variability and on the Chlorophyll map.",
  "InSeasonPRECO_AZOTE_TOUR3_INVERSE_CVIN_GOAL":"Goal: Adjust the nitrogen dose depending on the field variability.",
  "InSeasonPRECO_AZOTE_TOUR3_INVERSE_CVIN_DESC":"Adjust the nitrogen dose depending on the field variability and on the Chlorophyll map.",
  "RX_MAP_PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR4_INVERSE_CVIN": "N Rec. Round 4 Quality(Normal)",
  "PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR4_INVERSE_CVIN": "N Rec. Round 4 Quality (Normal)",
  "PRODUCT_TYPE_DISPLAY_TEXT_InSeasonPRECO_AZOTE_TOUR4_INVERSE_CVIN_WITHOUT": "N Rec. Round 4 Quality"